AllCops:
  TargetRubyVersion: 2.3

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/AbcSize:
  Max: 24
Metrics/ClassLength:
  Max: 400
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 24
Metrics/ModuleLength:
  Max: 300
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Naming/PredicateName:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

# Disable certain checks for tests
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "test/**/*"
Naming/FileName:
  Exclude:
    - "test/lookup-cases/**/*"
    - "lib/toys-core.rb"
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Exclude:
    - "test/**/*"
