AllCops:
  TargetRubyVersion: 2.3

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 400
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 400
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Style/GlobalVars:
  Exclude:
    - "test/lookup-cases/preloads/**/*.rb"
    - "test/test_loader.rb"
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets

# Disable certain checks for tests
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "test/**/*"
Naming/FileName:
  Exclude:
    - "test/lookup-cases/**/*"
    - "lib/toys-core.rb"
    - "examples/multi-file-gem/**/*.rb"
    - "examples/*/*.gemspec"
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Exclude:
    - "test/**/*"
