version: 2
jobs:
  test-ruby-2.3:
    docker:
       - image: circleci/ruby:2.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Toys CI
          command: ./toys-dev ci
  test-ruby-2.4:
    docker:
       - image: circleci/ruby:2.4-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Toys CI
          command: ./toys-dev ci
  test-ruby-2.5:
    docker:
       - image: circleci/ruby:2.5-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Toys CI
          command: ./toys-dev ci
  test-ruby-2.6:
    docker:
       - image: circleci/ruby:2.6-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Toys CI
          command: ./toys-dev ci
workflows:
  version: 2
  tests:
    jobs:
      - test-ruby-2.3
      - test-ruby-2.4
      - test-ruby-2.5
      - test-ruby-2.6
