version: 2.1
executors:
  ruby23:
    docker:
      - image: "circleci/ruby:2.3-stretch"
  ruby24:
    docker:
      - image: "circleci/ruby:2.4-stretch"
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-stretch"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-stretch"
commands:
  toys-ci:
    steps:
      - checkout
      - run:
          name: CI
          command: ./toys-dev do ci init , ci
jobs:
  test-ruby23:
    executor: ruby23
    steps:
      - toys-ci
  test-ruby24:
    executor: ruby24
    steps:
      - toys-ci
  test-ruby25:
    executor: ruby25
    steps:
      - toys-ci
  test-ruby26:
    executor: ruby26
    steps:
      - toys-ci
workflows:
  version: 2
  tests:
    jobs:
      - test-ruby23
      - test-ruby24
      - test-ruby25
      - test-ruby26
