version: 2.1
executors:
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-stretch"
commands:
  gh-pages-test:
    steps:
      - checkout
      - run:
          name: Test
          command: gem install toys && toys test
jobs:
  test:
    executor: ruby26
    steps:
      - gh-pages-test
workflows:
  version: 2
  tests:
    jobs:
      - test
