version: 2.1
executors:
  ruby23:
    docker:
      - image: "circleci/ruby:2.3-stretch"
  ruby24:
    docker:
      - image: "circleci/ruby:2.4-buster"
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-buster"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-buster"
  ruby27:
    docker:
      - image: "circleci/ruby:2.7-rc-buster"
  jruby:
    docker:
      - image: "circleci/jruby:latest"
    environment:
      JRUBY_OPTS: "--debug"
commands:
  toys-ci:
    steps:
      - checkout
      - run:
          name: CI
          command: ./toys-dev do ci init , ci
  toys-test:
    steps:
      - checkout
      - run:
          name: Test
          command: ./toys-dev do ci init , test
jobs:
  test-ruby23:
    executor: ruby23
    steps:
      - toys-test
  test-ruby24:
    executor: ruby24
    steps:
      - toys-test
  test-ruby25:
    executor: ruby25
    steps:
      - toys-test
  test-ruby26:
    executor: ruby26
    steps:
      - toys-ci
  test-ruby27:
    executor: ruby27
    steps:
      - toys-test
  test-jruby:
    executor: jruby
    steps:
      - toys-test
workflows:
  version: 2
  tests:
    jobs:
      - test-ruby23
      - test-ruby24
      - test-ruby25
      - test-ruby26
      - test-ruby27
      - test-jruby
